


CREATE TABLE ORGANIZATION
(
  PK_ID INT not null,
  LABEL varchar2(50) not null,
  payroll NUMBER(10,2),
  CONSTRAINT ORGANIZATION_PK PRIMARY KEY (PK_ID)
);



CREATE TABLE EMPLOYEE
(
  PK_ID INT not null,
  FK_ID_ORGANIZATION INT not null,
  LAST_NAME varchar2(50) not null,
  FIRST_NAME varchar2(50) not null,
  SALARY NUMBER(10,2),
  CONSTRAINT EMPLOYEE_PK PRIMARY KEY (PK_ID),
  CONSTRAINT EMPLOYEE_FK_ORGANIZATION FOREIGN KEY (FK_ID_ORGANIZATION) REFERENCES ORGANIZATION(PK_ID)
);

CREATE TABLE EMPLOYEE_SALARY_HISTORY
(
	PK_ID INT not null,
	FK_ID_EMPLOYEE INT not null,
	SALARY NUMBER(10,2),
	CONSTRAINT EMPLOYEE_SALARY_HISTORY_PK PRIMARY KEY (PK_ID),
	CONSTRAINT EMP_SAL_HIST_FK_EMP FOREIGN KEY (FK_ID_EMPLOYEE) REFERENCES EMPLOYEE(PK_ID)
);
CREATE SEQUENCE salary_history_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
commit;